

[rule]
author = ["Jarrett Sams"]
description = "Bat files observed in HTTP traffic on a port that is not the typical HTTP port 80."
from = "now-6m" # look-back time: 6 minutes. Change as needed.
name = "Bat files observed in HTTP traffic on Unusual Port"
risk_score = 13
severity = "low"
type = "query"
rule_id = "00000000-0000-0000-0000-000000000001"
query = '''
event.dataset: "zeek.http" and url.extension: bat and not destination.port: 80
'''

# if type is "threshold" instead, uncomment and modify below:
# [rule.threshold]
# field = ["host.hostname"]
# value = 100

[[rule.threat]] # Example Tactic, Technique, Sub-Technique. Change as needed.
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"

[[rule.threat.technique.subtechnique]]
id = "T1059.003"
name = "Windows Command Shell"
reference = "https://attack.mitre.org/techniques/T1059/003/"


[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"


# Optional Fields:
# throttle: 7d
# version: 1
# interval: 5m