[metadata]
creation_date = "2023/08/01"

[rule]
author = ["Jarrett Sams"]
description = "This alert looks for .zip files being sent off-network via FTP."
from = "now-6m" # look-back time: 6 minutes. Change as needed.
name = "Data Exfiltration Observed via FTP"
risk_score = 89
severity = "high"
type = "query"
rule_id = "00000000-0000-0000-0000-000000000003"
query = '''
event.dataset: zeek.ftp and event.action: STOR and zeek.ftp.args: *.zip
'''

# if type is "threshold" instead, uncomment and modify below:
# [rule.threshold]
# field = ["host.hostname"]
# value = 100

[[rule.threat]] # Example Tactic, Technique, Sub-Technique. Change as needed.
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1020"
name = "Automated Exfiltration"
reference = "https://attack.mitre.org/techniques/T1020/"

[rule.threat.tactic]
id = "TA0010"
name = "Exfiltration"
reference = "https://attack.mitre.org/tactics/TA0010/"



# Optional Fields:
# throttle: 7d
# version: 1
# interval: 5m