[rule]
author = ["Jarrett Sams"]
description = "From looking at sysmon_operational logs, we're triggering on Powershell running from a bat file execution."
from = "now-6m" # look-back time: 6 minutes. Change as needed.
name = "Powershell Execution via a BAT file"
risk_score = 25
severity = "low"
type = "query"
rule_id = "00000000-0000-0000-0000-000000000006"
query = '''
event.dataset: "windows.sysmon_operational" and process.command_line: powershell* and process.parent.command_line: *bat* and process.parent.name: cmd.exe
'''

# if type is "threshold" instead, uncomment and modify below:
# [rule.threshold]
# field = ["host.hostname"]
# value = 100

[[rule.threat]] # Example Tactic, Technique, Sub-Technique. Change as needed.
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1059"
name = "Command and Scripting Interpreter"
reference = "https://attack.mitre.org/techniques/T1059/"

[[rule.threat.technique.subtechnique]]
id = "T1059.001"
name = "PowerShell"
reference = "https://attack.mitre.org/techniques/T1059/001/"


[rule.threat.tactic]
id = "TA0002"
name = "Execution"
reference = "https://attack.mitre.org/tactics/TA0002/"


# Optional Fields:
# throttle: 7d
# version: 1
# interval: 5m