name: Send Detections to Elastic

on:
  workflow_dispatch:

jobs:
  elastic-detections-send:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'
      - run: pip install requests
      - run: python development/toml_to_json.py



