name: Update Elastic Detections

on:
  push:
    path:
      '**.toml'
  workflow_dispatch:

jobs:
  elastic-detections-updated:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.5'
      
      # steps.changed-files.outputs.all_changed_files object    
      - name: Get Updated/Changed Files
        id: changed-files
      - uses: tj-actions/changed-files@v39
      
      - name: Run Update Script
        env:
          ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        - run: pip install requests
        - run: python development/update_alert.py


